name: Continuous Integration

on:
  push:
    branches: [ "main" ] # Runs when you push to main
  pull_request:
    branches: [ "main" ] # Runs when you create/update a PR

jobs:
  build-and-test: 
    runs-on: ubuntu-latest # use the latest Ubuntu runner on Githubs servers
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3 #downloads your repository code to the runner

      - name: Set up Python
        uses: actions/setup-python@v4 #install python 3.12
        with:
          python-version: '3.12'

      - name: Install uv
        run: pip install uv

      - name: Install dependencies
        run: uv sync --frozen

      - name: Run unit and integration tests
        run: uv run pytest -q

      - name: Check Terraform formatting
        run: terraform fmt -check -recursive

      - name: Initialize Terraform
        working-directory: terraform
        run: terraform init -backend=false

      - name: Validate Terraform configuration
        working-directory: terraform
        run: terraform validate